import React, { useState } from 'react';
import { Menu, X } from 'lucide-react';
interface NavbarProps { onOpenEmployerModal: (serviceId?: string) => void; onNavigateToJobs: () => void; onOpenCandidateRegister: () => void; onOpenDocumentsModal: () => void; }
export const Navbar: React.FC<NavbarProps> = ({ onOpenEmployerModal, onNavigateToJobs }) => {
  const [open, setOpen] = useState(false);
  const links = [{ label: 'Find a Job', href: '#jobs' }, { label: 'For Employers', href: '#employers' }, { label: 'Services', href: '#services' }, { label: 'About Us', href: '#about' }, { label: 'Resources', href: '#gallery' }, { label: 'Contact', href: '#contact' }];
  const action = (label: string) => { setOpen(false); if (label === 'Find a Job') onNavigateToJobs(); else if (label === 'Hire Staff') onOpenEmployerModal(); else document.querySelector(links.find((item) => item.label === label)?.href || '#')?.scrollIntoView({ behavior: 'smooth' }); };
  return <header className="site-header"><div className="nav-inner"><a href="#top" className="wordmark" aria-label="Strata Workforce home">STRATA<span>WORKFORCE</span></a><nav className="desktop-nav">{links.map((item) => <a key={item.label} href={item.href}>{item.label}</a>)}</nav><div className="nav-actions"><button className="nav-job" onClick={() => action('Find a Job')}>Find a Job</button><button className="nav-hire" onClick={() => action('Hire Staff')}>Hire Staff</button></div><button className="menu-toggle" aria-expanded={open} aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div>{open && <nav className="mobile-nav"><div className="mobile-nav-actions"><button onClick={() => action('Find a Job')}>Find a Job</button><button onClick={() => action('Hire Staff')}>Hire Staff</button></div>{links.map((item) => <a key={item.label} href={item.href} onClick={() => setOpen(false)}>{item.label}</a>)}</nav>}</header>;
};
